controller_list:
 - name: yanshee/left_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - left_arm1_joint
     - left_arm2_joint
     - left_arm3_joint


 - name: yanshee/right_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true

   joints:
     - right_arm1_joint
     - right_arm2_joint
     - right_arm3_joint

 - name: yanshee/left_leg_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true

   joints:
     - left_leg1_joint
     - left_leg2_joint
     - left_leg3_joint
     - left_leg4_joint
     - left_leg5_joint

 - name: yanshee/right_leg_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true

   joints:
     - right_leg1_joint
     - right_leg2_joint
     - right_leg3_joint
     - right_leg4_joint
     - right_leg5_joint




