controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_arm1_joint
      - left_arm2_joint
      - left_arm3_joint
  - name: fake_right_arm_controller
    joints:
      - right_arm1_joint
      - right_arm2_joint
      - right_arm3_joint
  - name: fake_left_leg_controller
    joints:
      - left_leg1_joint
      - left_leg2_joint
      - left_leg3_joint
      - left_leg4_joint
      - left_leg5_joint
  - name: fake_right_leg_controller
    joints:
      - right_leg1_joint
      - right_leg2_joint
      - right_leg3_joint
      - right_leg4_joint
      - right_leg5_joint